version: '3'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    env_file: colourinput.env
    volumes:
      - ./inputFile:/csvserver/inputdata
  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"
    env_file: colourinput.env
    volumes:
      - ./prometheus:/etc/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - csvserver
volumes:
  prometheus:
